'use strict';

const ITEMS = {
  plants: [
    { id: 'catnip',     name: 'Catnip',       cost: 0,   emoji: '🌿', desc: 'Irresistible to all cats.',         attract: ['energetic','curious'],  w: 1, h: 1 },
    { id: 'sunflower',  name: 'Sunflower',     cost: 15,  emoji: '🌻', desc: 'Sunny cats love this.',             attract: ['lazy','elegant'],        w: 1, h: 1 },
    { id: 'tallgrass',  name: 'Tall Grass',    cost: 10,  emoji: '🌾', desc: 'Shy cats hide here.',              attract: ['shy','cautious'],        w: 1, h: 1 },
    { id: 'mushroom',   name: 'Mushroom',      cost: 20,  emoji: '🍄', desc: 'Attracts curious wanderers.',       attract: ['curious','playful'],     w: 1, h: 1 },
    { id: 'cherrytree', name: 'Cherry Tree',   cost: 50,  emoji: '🌸', desc: 'Elegant cats adore blossoms.',      attract: ['elegant','royal'],       w: 2, h: 2 },
    { id: 'pond',       name: 'Garden Pond',   cost: 60,  emoji: '🪷', desc: 'Fishing cats appear nearby.',       attract: ['patient','fishcat'],     w: 2, h: 1 },
  ],
  furniture: [
    { id: 'box',        name: 'Cardboard Box', cost: 0,   emoji: '📦', desc: 'A classic. Every cat loves one.',   attract: ['lazy','curious'],        w: 1, h: 1 },
    { id: 'cattree',    name: 'Cat Tree',      cost: 40,  emoji: '🌴', desc: 'High perches attract royalty.',      attract: ['elegant','energetic'],   w: 1, h: 2 },
    { id: 'hammock',    name: 'Hammock',       cost: 35,  emoji: '🪑', desc: 'Lazy nappers will migrate here.',    attract: ['lazy','gentle'],         w: 2, h: 1 },
    { id: 'shelf',      name: 'Wooden Shelf',  cost: 45,  emoji: '🪵', desc: 'Collectors and climbers love it.',   attract: ['curious','elegant'],     w: 2, h: 1 },
    { id: 'cozycorner', name: 'Cozy Corner',   cost: 55,  emoji: '🏮', desc: 'Shy cats feel safe here.',          attract: ['shy','cautious'],        w: 1, h: 1 },
  ],
  toys: [
    { id: 'ball',       name: 'Yarn Ball',     cost: 0,   emoji: '🧶', desc: 'Simple fun for every cat.',         attract: ['playful','energetic'],   w: 1, h: 1 },
    { id: 'feather',    name: 'Feather Wand',  cost: 20,  emoji: '🪶', desc: 'Playful cats go wild for this.',    attract: ['energetic','curious'],   w: 1, h: 1 },
    { id: 'fishbowl',   name: 'Fish Bowl',     cost: 30,  emoji: '🐠', desc: 'Mesmerizes patient hunters.',       attract: ['patient','fishcat'],     w: 1, h: 1 },
    { id: 'laserspot',  name: 'Laser Spot',    cost: 25,  emoji: '🔴', desc: 'Energetic cats lose their minds.',  attract: ['energetic','playful'],   w: 1, h: 1 },
    { id: 'tunnel',     name: 'Play Tunnel',   cost: 40,  emoji: '🌀', desc: 'Shy and playful cats love to hide.', attract: ['shy','playful'],        w: 2, h: 1 },
  ],
  decor: [
    { id: 'lantern',    name: 'Stone Lantern', cost: 25,  emoji: '🏮', desc: 'Creates a warm, calm glow.',        attract: ['gentle','shy'],          w: 1, h: 1 },
    { id: 'statue',     name: 'Cat Statue',    cost: 35,  emoji: '🗿', desc: 'Other cats respect the statue.',    attract: ['royal','elegant'],       w: 1, h: 1 },
    { id: 'fountain',   name: 'Fountain',      cost: 55,  emoji: '⛲', desc: 'Fresh water draws all visitors.',   attract: ['all'],                   w: 1, h: 1 },
    { id: 'windchime',  name: 'Wind Chime',    cost: 30,  emoji: '🎐', desc: 'Music calms shy visitors.',         attract: ['shy','gentle'],          w: 1, h: 1 },
    { id: 'cushion',    name: 'Plush Cushion', cost: 20,  emoji: '🛋️', desc: 'The fluffiest nap spot.',           attract: ['lazy','gentle'],         w: 1, h: 1 },
  ],
};

const CAT_DEFS = [
  {
    id: 'muffin',
    name: 'Muffin',
    personality: 'Lazy',
    color: '#e8c49a',
    markings: 'tabby',
    favItems: ['box','hammock','cushion'],
    traits: ['lazy','gentle'],
    rarity: 'common',
    giftChance: 0.4,
    gifts: [5, 8, 12],
    thoughts: ['💤 Nap time...','😌 So cozy...','🌞 Warm...','💭 Dreams of tuna'],
    speed: 0.3,
    unlocked: true,
  },
  {
    id: 'shadow',
    name: 'Shadow',
    personality: 'Shy',
    color: '#5a5a7a',
    markings: 'solid',
    favItems: ['tallgrass','cozycorner','windchime'],
    traits: ['shy','cautious'],
    rarity: 'uncommon',
    giftChance: 0.6,
    gifts: [10, 18, 25],
    thoughts: ['👀 Watching...','🌑 The shadows...','💎 Shiny gift!','🤫 Shhh...'],
    speed: 0.5,
    unlocked: true,
  },
  {
    id: 'zoom',
    name: 'Zoom',
    personality: 'Energetic',
    color: '#f4a261',
    markings: 'striped',
    favItems: ['laserspot','feather','ball'],
    traits: ['energetic','playful'],
    rarity: 'common',
    giftChance: 0.3,
    gifts: [3, 6, 10],
    thoughts: ['⚡ ZOOM!','🏃 Faster!','🎾 Must catch!','💨 Wheee!'],
    speed: 1.4,
    unlocked: true,
  },
  {
    id: 'princess',
    name: 'Princess',
    personality: 'Elegant',
    color: '#f9c6d0',
    markings: 'bicolor',
    favItems: ['cherrytree','cattree','statue'],
    traits: ['elegant','royal'],
    rarity: 'uncommon',
    giftChance: 0.5,
    gifts: [15, 25, 40],
    thoughts: ['👑 Bow to me','🌸 Lovely...','💅 Impeccable','🎀 Perfection'],
    speed: 0.55,
    unlocked: true,
  },
  {
    id: 'biscuit',
    name: 'Biscuit',
    personality: 'Curious',
    color: '#d4a76a',
    markings: 'calico',
    favItems: ['mushroom','feather','shelf'],
    traits: ['curious','playful'],
    rarity: 'common',
    giftChance: 0.35,
    gifts: [4, 8, 14],
    thoughts: ['🔍 What\'s this?','👃 Sniff sniff','✨ Ooh shiny!','🧐 Interesting...'],
    speed: 0.7,
    unlocked: true,
  },
  {
    id: 'bubbles',
    name: 'Bubbles',
    personality: 'Gentle',
    color: '#a8d8ea',
    markings: 'tuxedo',
    favItems: ['pond','fishbowl','fountain'],
    traits: ['gentle','patient'],
    rarity: 'uncommon',
    giftChance: 0.5,
    gifts: [8, 15, 22],
    thoughts: ['💧 Drip drop...','🐟 Fishies~','😊 Peaceful','🫧 Bubbles!'],
    speed: 0.45,
    unlocked: true,
  },
  {
    id: 'duke',
    name: 'Duke',
    personality: 'Royal',
    color: '#6b4c3b',
    markings: 'solid',
    favItems: ['statue','shelf','pond'],
    traits: ['royal','patient'],
    rarity: 'rare',
    giftChance: 0.7,
    gifts: [25, 45, 70],
    thoughts: ['🎩 Distinguished','📜 Hmm, yes...','🍷 Refined taste','⚜️ My garden'],
    speed: 0.4,
    unlocked: false,
    unlockCost: 80,
  },
  {
    id: 'marble',
    name: 'Marble',
    personality: 'Mysterious',
    color: '#c0c0c0',
    markings: 'spotted',
    favItems: ['cozycorner','lantern','windchime'],
    traits: ['shy','curious'],
    rarity: 'rare',
    giftChance: 0.65,
    gifts: [20, 35, 60],
    thoughts: ['🌙 Moonlit paths','🔮 I see things...','✨ Magic nearby','🌀 Spinning...'],
    speed: 0.6,
    unlocked: false,
    unlockCost: 100,
  },
];

const SEASONS = [
  { name: 'Spring', emoji: '🌸', palette: { sky: '#c9e8ff', ground: '#8fbc6a', accent: '#f9b3cc' } },
  { name: 'Summer', emoji: '☀️', palette: { sky: '#87ceeb', ground: '#6aaa40', accent: '#ffe066' } },
  { name: 'Autumn', emoji: '🍂', palette: { sky: '#d4a96a', ground: '#9a7a45', accent: '#e07a2a' } },
  { name: 'Winter', emoji: '❄️', palette: { sky: '#c5dff8', ground: '#d8eef8', accent: '#9ac4f5' } },
];
